### ISSUE TITLE
Version numbers in every module (including contrib scripts)

### ISSUE THREAD

**Issue by iLoveTux** [McIndi/mast#18]
I can't believe that this isn't the case already, but it would help troubleshooting problems tremendously if everything had knowledge of its own version so we could accept a `-v, --version` parameter and get an accurate version number. The only question is to version things separately or one universal version number.

I vote for individual version numbers so we can keep up with a rolling release like we've been doing. One compromise might be to use a universal version number for the MAST version and a suffix specifying the modules version. for example we could have a modules version be `version 2.1.0-0` and the next version of that module would be `version 2.1.0-1`.

@briankearney @mharden108 @steveyeof @jimb400 

Thoughts, questions, ideas? All welcome below.

**Comment by steveyeof** [comment]
If you have something that’s well along, go with it. It is important from a support point of view to be able to query the exact version of a MAST installation whenever it’s implemented. This also extends to 3rd party software we’re utilizing, in so far as knowing the versions that correspond to MAST releases (I believe github can already do this). There is a need to develop and document the policies and standards that govern MAST version designations, as well as how we handle those of 3rd parties. Brian wants to do a thorough deep dive on this since has so many aspects, more on that later.
I wanted to know what would be the progression of numbering at the mast & module level with an individual version numbering scheme as you suggested? Got any details?
I have put together a spread sheet summarizing my understanding of the “compromise using a universal version number for the MAST version and a suffix specifying the modules version.”  See the attached spread sheet, let me know if I’m close.
[Compromise_versioning_test.xlsx](https://github.com/McIndi/mast/files/198583/Compromise_versioning_test.xlsx)

**Comment by iLoveTux** [comment]
I'm definitely willing to go through a deep-dive, but I think that we are getting way too complex here, maybe not  but that's the thing with gut feelings.

I propose that we keep things simple. Here is a simple plan that I think might work:

1. Official releases should be one week apart released on Friday.
2. We decide through discussions about requirements,resources and time what will be in the next version. This is done by reviewing the issues open in GitHub and assigning the included tasks to a milestone.
3. When a release is made, all individual modules version suffixes are set to 0.
4. As fixes and enhancements are made throughout the week, the affected modules suffix increment by one.
5. The only third party dependency we need to track is Anaconda which tracks its own dependency versions. GitHub will track anything not included in Anaconda, we just go with the latest.
    * If we are not tracking these external versions, we should create a script to gather the installed package versions, so we can see what the customer is using just by them running one command.

**Comment by steveyeof** [comment]
The simple plan looks good to me, and if a script is all it takes to complete, great.
Regarding item 2 from 3/31/16, here are some points for consideration as we define the process further.
•	For MAST version changes, will there be (at least internally) a target release date or a minimal set of features as the release criteria
•	Will there be a feature inclusion cutoff date, if so, how long does it need to be before the target release date.
•	Such a cutoff to “finalize” next version features, allows time to begin documentation and perform necessary testing.
•	Time will always have to allotted for bug fixes and priority requests, which may argue for major MAST version releases to be based on feature completion rather than a calendar date.
•	Non bug fixes (such as priority requests) after the cutoff date do not necessarily have to be in the first release of the new version, depending on testing and documentation constraints.
•	With constant integration (weekly releases) in place, major version changes may represent only an incremental change from the sum of weekly updates. This has some marketing implications to be addressed outside the scope of this issue.

**Comment by iLoveTux** [comment]
OK, so I just want to be clear that I'm brainstorming here, so everything is subject to change, but going along this route of thought:

responding in order to your questions/comments:

* Minor (ie the x in 2.1.x)MAST version changes will be targeted for every Friday, Major versions will be released on a Friday, but based on feature completion. It will be acceptable to re-target a feature to a new minor version, but not to a new major version
* For the feature inclusion cut-off date we should hold a meeting every Monday (we can use Hangouts) to discuss the features to be released the following Friday (as long as this is a minor version, we can later push a feature back if we need to)
* Documentation and testing should be done as part of and at the same time as the development.
* Because the feature list for each minor release is tentative, we can plan for the best case scenario and later decide that a bug fix caused a feature to be postponed. I do propose that major versions are to be feature based.
* There should be no testing or documentation constraints as they are to be considered as development constraints and scheduled as such.
* Since major versions are to be feature based and will take the place of one minor release (meaning that some Friday instead of a minor version we will release a major version), we will have at least one set of new changes to be released (This will probably consist of features which require a longer development time), for instance (and this is subject to change), when the new deployment script, enable/disable debug logging as well as enable/disable probe features are complete, I would consider us to have reached version 2.2.0, everything before that will be a minor release.

**Comment by iLoveTux** [comment]
So below is what I think of for implementation, I'm leaving it here for discussion as it might take some time to implement, but this is the quickest way I could think of to implement:

1. Have `mast` (on linux) and `mast.bat` on Windows set an environment variable with the MAST version.
2. Have each Script and module set a `__version__` variable constructed with this environment variable along with it's own suffix.
3. Have the script suggested in [this issue](https://github.com/McIndi/mast/issues/21) grab all the versions and put them in a file which users can post along with their issues.

**Comment by steveyeof** [comment]
This sounds good, where do we retrieve or access the Anaconda version associated with the MAST release?

**Comment by iLoveTux** [comment]
We can leverage `conda` to grab all the relevant (non-mast) versions.

**Comment by iLoveTux** [comment]
This is implemented, needs to be refined...will open a new issue to really nail down our versioning scheme.
