### ISSUE TITLE
Why has the MAST 2.1.1 Windows 64 installer ballooned to 713mb?

### ISSUE THREAD

**Issue by briankearney** [McIndi/mast#47]
![mast-211-win-64-install-download](https://cloud.githubusercontent.com/assets/7741846/15160736/2a0573b8-16c9-11e6-9b24-9548697eb5f6.png)
#### _Issue template for MAST for IBM DataPower_

_Please give a brief description of the issue you are having_
The MAST 2.1.1 Windows 64 installer ballooned to 713mb but there is not *that* much more to MAST

_Please answer each question as best as you can_

1. **What were you trying to do?** Download MAST_2.1.1_Windows-64_install.exe
2. **What were you expecting to happen?** A file download of around 350mb
3. **What were the actual results?** A file download of 713mb
4. **Was this a fresh install of MAST or when was the last time you installed a hotfix?** A fresh install
5. **Please provide any output from the command (If in the web gui click the `history` link in the output and paste that).** See the attached screenshot

Thank you for taking the time to submit an issue, this is the only way we can continue to improve MAST in response to our customers needs.

**Comment by iLoveTux** [comment]
This is an issue with an early attempt at our automated build process and will be fixed in the next release.

Basically what had happened is that since both the 32 and 64 bit Windows installers were being built on the same machine, both Anaconda installers were present, so when it came time to package it all up the build script grabbed both, so while only one would be executed by the install process, the installer is carrying both of them around.
